{{- if and .Values.webUI.enabled .Values.webUI.tls.acmeCACert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "usg-tftp.fullname" . }}-acme-ca
  labels:
    {{- include "usg-tftp.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.webUI.tls.acmeCACert }}
{{- end }}
